/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d3dbe2",
        "secondary": "#5b5f67",
        "surface-bright": "#f9f9fb",
        "on-error-container": "#752121",
        "on-primary": "#f7f7fa",
        "surface-container-low": "#f2f4f7",
        "surface": "#f9f9fb",
        "surface-container": "#ebeef2",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#303c53",
        "secondary-container": "#dfe2eb",
        "error-container": "#fe8983",
        "error": "#9f403d",
        "tertiary-fixed": "#d1ddfa",
        "outline": "#757c81",
        "secondary-fixed-dim": "#d1d4dd",
        "on-tertiary-container": "#434e66",
        "primary-fixed-dim": "#d4d4d7",
        "on-primary-container": "#505254",
        "secondary-fixed": "#dfe2eb",
        "on-primary-fixed": "#3e3f42",
        "surface-container-highest": "#dde3e9",
        "primary-fixed": "#e2e2e5",
        "tertiary-fixed-dim": "#c3cfeb",
        "secondary-dim": "#4f535a",
        "on-surface": "#2d3338",
        "on-error": "#fff7f6",
        "primary-container": "#e2e2e5",
        "tertiary": "#545f78",
        "tertiary-dim": "#48536b",
        "primary": "#5d5e61",
        "inverse-on-surface": "#9c9d9f",
        "inverse-surface": "#0c0e10",
        "on-tertiary": "#f9f8ff",
        "surface-variant": "#dde3e9",
        "on-primary-fixed-variant": "#5a5c5e",
        "on-secondary-container": "#4e5259",
        "inverse-primary": "#f9f9fc",
        "on-secondary": "#f7f9ff",
        "error-dim": "#4e0309",
        "on-surface-variant": "#596065",
        "on-secondary-fixed": "#3b4046",
        "outline-variant": "#acb3b8",
        "on-secondary-fixed-variant": "#585c63",
        "background": "#f9f9fb",
        "surface-tint": "#5d5e61",
        "primary-dim": "#515255",
        "tertiary-container": "#d1ddfa",
        "on-background": "#2d3338",
        "surface-container-high": "#e4e9ee",
        "on-tertiary-fixed-variant": "#4d5870"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [],
}
